// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: api/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopRequestParam int32

const (
	TopRequestParam_VIEWS    TopRequestParam = 0
	TopRequestParam_LIKES    TopRequestParam = 1
	TopRequestParam_COMMENTS TopRequestParam = 2
)

// Enum value maps for TopRequestParam.
var (
	TopRequestParam_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	TopRequestParam_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x TopRequestParam) Enum() *TopRequestParam {
	p := new(TopRequestParam)
	*p = x
	return p
}

func (x TopRequestParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopRequestParam) Descriptor() protoreflect.EnumDescriptor {
	return file_api_stats_proto_enumTypes[0].Descriptor()
}

func (TopRequestParam) Type() protoreflect.EnumType {
	return &file_api_stats_proto_enumTypes[0]
}

func (x TopRequestParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopRequestParam.Descriptor instead.
func (TopRequestParam) EnumDescriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{0}
}

// Request message for getting post stats
type GetPostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsRequest) Reset() {
	*x = GetPostStatsRequest{}
	mi := &file_api_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsRequest) ProtoMessage() {}

func (x *GetPostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// Response message for post stats
type PostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      int64                  `protobuf:"varint,1,opt,name=comments,proto3" json:"comments,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Views         int64                  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsResponse) Reset() {
	*x = PostStatsResponse{}
	mi := &file_api_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsResponse) ProtoMessage() {}

func (x *PostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsResponse.ProtoReflect.Descriptor instead.
func (*PostStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PostStatsResponse) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *PostStatsResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PostStatsResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

// Request message for getting post dynamics
type GetPostDynamicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDynamicsRequest) Reset() {
	*x = GetPostDynamicsRequest{}
	mi := &file_api_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDynamicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDynamicsRequest) ProtoMessage() {}

func (x *GetPostDynamicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDynamicsRequest.ProtoReflect.Descriptor instead.
func (*GetPostDynamicsRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostDynamicsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// Response message for post dynamics
type PostDynamicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*PostDynamicsItem    `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	Likes         []*PostDynamicsItem    `protobuf:"bytes,2,rep,name=likes,proto3" json:"likes,omitempty"`
	Comments      []*PostDynamicsItem    `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDynamicsResponse) Reset() {
	*x = PostDynamicsResponse{}
	mi := &file_api_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDynamicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDynamicsResponse) ProtoMessage() {}

func (x *PostDynamicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDynamicsResponse.ProtoReflect.Descriptor instead.
func (*PostDynamicsResponse) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{3}
}

func (x *PostDynamicsResponse) GetViews() []*PostDynamicsItem {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *PostDynamicsResponse) GetLikes() []*PostDynamicsItem {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *PostDynamicsResponse) GetComments() []*PostDynamicsItem {
	if x != nil {
		return x.Comments
	}
	return nil
}

// Post dynamics item
type PostDynamicsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDynamicsItem) Reset() {
	*x = PostDynamicsItem{}
	mi := &file_api_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDynamicsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDynamicsItem) ProtoMessage() {}

func (x *PostDynamicsItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDynamicsItem.ProtoReflect.Descriptor instead.
func (*PostDynamicsItem) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{4}
}

func (x *PostDynamicsItem) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *PostDynamicsItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Request message for getting top posts
type GetTopPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         TopRequestParam        `protobuf:"varint,1,opt,name=param,proto3,enum=stats.v1.TopRequestParam" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPostsRequest) Reset() {
	*x = GetTopPostsRequest{}
	mi := &file_api_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsRequest) ProtoMessage() {}

func (x *GetTopPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsRequest.ProtoReflect.Descriptor instead.
func (*GetTopPostsRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopPostsRequest) GetParam() TopRequestParam {
	if x != nil {
		return x.Param
	}
	return TopRequestParam_VIEWS
}

// Request message for getting top users
type GetTopUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         TopRequestParam        `protobuf:"varint,1,opt,name=param,proto3,enum=stats.v1.TopRequestParam" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersRequest) Reset() {
	*x = GetTopUsersRequest{}
	mi := &file_api_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersRequest) ProtoMessage() {}

func (x *GetTopUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersRequest.ProtoReflect.Descriptor instead.
func (*GetTopUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopUsersRequest) GetParam() TopRequestParam {
	if x != nil {
		return x.Param
	}
	return TopRequestParam_VIEWS
}

// Request message for top posts
type TopPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsRequest) Reset() {
	*x = TopPostsRequest{}
	mi := &file_api_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsRequest) ProtoMessage() {}

func (x *TopPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsRequest.ProtoReflect.Descriptor instead.
func (*TopPostsRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopPostsRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// Request message for top users
type TopUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersRequest) Reset() {
	*x = TopUsersRequest{}
	mi := &file_api_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersRequest) ProtoMessage() {}

func (x *TopUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersRequest.ProtoReflect.Descriptor instead.
func (*TopUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{8}
}

func (x *TopUsersRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// Top posts item
type TopPostsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Views         int64                  `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int64                  `protobuf:"varint,4,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsItem) Reset() {
	*x = TopPostsItem{}
	mi := &file_api_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsItem) ProtoMessage() {}

func (x *TopPostsItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsItem.ProtoReflect.Descriptor instead.
func (*TopPostsItem) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{9}
}

func (x *TopPostsItem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *TopPostsItem) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *TopPostsItem) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *TopPostsItem) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

// Response message for top posts
type TopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopPosts      []*TopPostsItem        `protobuf:"bytes,1,rep,name=top_posts,json=topPosts,proto3" json:"top_posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsResponse) Reset() {
	*x = TopPostsResponse{}
	mi := &file_api_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsResponse) ProtoMessage() {}

func (x *TopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsResponse.ProtoReflect.Descriptor instead.
func (*TopPostsResponse) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{10}
}

func (x *TopPostsResponse) GetTopPosts() []*TopPostsItem {
	if x != nil {
		return x.TopPosts
	}
	return nil
}

// Top users item
type TopUsersItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Views         int64                  `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int64                  `protobuf:"varint,4,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersItem) Reset() {
	*x = TopUsersItem{}
	mi := &file_api_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersItem) ProtoMessage() {}

func (x *TopUsersItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersItem.ProtoReflect.Descriptor instead.
func (*TopUsersItem) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{11}
}

func (x *TopUsersItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopUsersItem) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *TopUsersItem) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *TopUsersItem) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

// Response message for top users
type TopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUsers      []*TopUsersItem        `protobuf:"bytes,1,rep,name=top_users,json=topUsers,proto3" json:"top_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersResponse) Reset() {
	*x = TopUsersResponse{}
	mi := &file_api_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersResponse) ProtoMessage() {}

func (x *TopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersResponse.ProtoReflect.Descriptor instead.
func (*TopUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{12}
}

func (x *TopUsersResponse) GetTopUsers() []*TopUsersItem {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

var File_api_stats_proto protoreflect.FileDescriptor

var file_api_stats_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x11, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x14, 0x50, 0x6f,
	0x73, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x58,
	0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f,
	0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22,
	0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x27, 0x0a, 0x0f, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22,
	0x27, 0x0a, 0x0f, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x6f, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x10, 0x54, 0x6f, 0x70,
	0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x09, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x22, 0x6f, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x10, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2a, 0x35, 0x0a, 0x0f,
	0x54, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x49, 0x45, 0x57, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49,
	0x4b, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54,
	0x53, 0x10, 0x02, 0x32, 0xc9, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x17, 0x5a, 0x15, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_stats_proto_rawDescOnce sync.Once
	file_api_stats_proto_rawDescData []byte
)

func file_api_stats_proto_rawDescGZIP() []byte {
	file_api_stats_proto_rawDescOnce.Do(func() {
		file_api_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stats_proto_rawDesc), len(file_api_stats_proto_rawDesc)))
	})
	return file_api_stats_proto_rawDescData
}

var file_api_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_stats_proto_goTypes = []any{
	(TopRequestParam)(0),           // 0: stats.v1.TopRequestParam
	(*GetPostStatsRequest)(nil),    // 1: stats.v1.GetPostStatsRequest
	(*PostStatsResponse)(nil),      // 2: stats.v1.PostStatsResponse
	(*GetPostDynamicsRequest)(nil), // 3: stats.v1.GetPostDynamicsRequest
	(*PostDynamicsResponse)(nil),   // 4: stats.v1.PostDynamicsResponse
	(*PostDynamicsItem)(nil),       // 5: stats.v1.PostDynamicsItem
	(*GetTopPostsRequest)(nil),     // 6: stats.v1.GetTopPostsRequest
	(*GetTopUsersRequest)(nil),     // 7: stats.v1.GetTopUsersRequest
	(*TopPostsRequest)(nil),        // 8: stats.v1.TopPostsRequest
	(*TopUsersRequest)(nil),        // 9: stats.v1.TopUsersRequest
	(*TopPostsItem)(nil),           // 10: stats.v1.TopPostsItem
	(*TopPostsResponse)(nil),       // 11: stats.v1.TopPostsResponse
	(*TopUsersItem)(nil),           // 12: stats.v1.TopUsersItem
	(*TopUsersResponse)(nil),       // 13: stats.v1.TopUsersResponse
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_api_stats_proto_depIdxs = []int32{
	5,  // 0: stats.v1.PostDynamicsResponse.views:type_name -> stats.v1.PostDynamicsItem
	5,  // 1: stats.v1.PostDynamicsResponse.likes:type_name -> stats.v1.PostDynamicsItem
	5,  // 2: stats.v1.PostDynamicsResponse.comments:type_name -> stats.v1.PostDynamicsItem
	14, // 3: stats.v1.PostDynamicsItem.date:type_name -> google.protobuf.Timestamp
	0,  // 4: stats.v1.GetTopPostsRequest.param:type_name -> stats.v1.TopRequestParam
	0,  // 5: stats.v1.GetTopUsersRequest.param:type_name -> stats.v1.TopRequestParam
	10, // 6: stats.v1.TopPostsResponse.top_posts:type_name -> stats.v1.TopPostsItem
	12, // 7: stats.v1.TopUsersResponse.top_users:type_name -> stats.v1.TopUsersItem
	1,  // 8: stats.v1.StatsService.GetPostStats:input_type -> stats.v1.GetPostStatsRequest
	3,  // 9: stats.v1.StatsService.GetPostDynamics:input_type -> stats.v1.GetPostDynamicsRequest
	6,  // 10: stats.v1.StatsService.GetTopPosts:input_type -> stats.v1.GetTopPostsRequest
	7,  // 11: stats.v1.StatsService.GetTopUsers:input_type -> stats.v1.GetTopUsersRequest
	2,  // 12: stats.v1.StatsService.GetPostStats:output_type -> stats.v1.PostStatsResponse
	4,  // 13: stats.v1.StatsService.GetPostDynamics:output_type -> stats.v1.PostDynamicsResponse
	11, // 14: stats.v1.StatsService.GetTopPosts:output_type -> stats.v1.TopPostsResponse
	13, // 15: stats.v1.StatsService.GetTopUsers:output_type -> stats.v1.TopUsersResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_stats_proto_init() }
func file_api_stats_proto_init() {
	if File_api_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stats_proto_rawDesc), len(file_api_stats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stats_proto_goTypes,
		DependencyIndexes: file_api_stats_proto_depIdxs,
		EnumInfos:         file_api_stats_proto_enumTypes,
		MessageInfos:      file_api_stats_proto_msgTypes,
	}.Build()
	File_api_stats_proto = out.File
	file_api_stats_proto_goTypes = nil
	file_api_stats_proto_depIdxs = nil
}
