// Code generated by MockGen. DO NOT EDIT.
// Source: sn/libraries/proto/stats (interfaces: StatsServiceClient)

// Package stats_mocks is a generated GoMock package.
package stats_mocks

import (
	context "context"
	reflect "reflect"
	stats "sn/libraries/proto/stats"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockStatsServiceClient is a mock of StatsServiceClient interface.
type MockStatsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceClientMockRecorder
}

// MockStatsServiceClientMockRecorder is the mock recorder for MockStatsServiceClient.
type MockStatsServiceClientMockRecorder struct {
	mock *MockStatsServiceClient
}

// NewMockStatsServiceClient creates a new mock instance.
func NewMockStatsServiceClient(ctrl *gomock.Controller) *MockStatsServiceClient {
	mock := &MockStatsServiceClient{ctrl: ctrl}
	mock.recorder = &MockStatsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsServiceClient) EXPECT() *MockStatsServiceClientMockRecorder {
	return m.recorder
}

// GetPostDynamics mocks base method.
func (m *MockStatsServiceClient) GetPostDynamics(arg0 context.Context, arg1 *stats.GetPostDynamicsRequest, arg2 ...grpc.CallOption) (*stats.PostDynamicsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostDynamics", varargs...)
	ret0, _ := ret[0].(*stats.PostDynamicsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostDynamics indicates an expected call of GetPostDynamics.
func (mr *MockStatsServiceClientMockRecorder) GetPostDynamics(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostDynamics", reflect.TypeOf((*MockStatsServiceClient)(nil).GetPostDynamics), varargs...)
}

// GetPostStats mocks base method.
func (m *MockStatsServiceClient) GetPostStats(arg0 context.Context, arg1 *stats.GetPostStatsRequest, arg2 ...grpc.CallOption) (*stats.PostStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostStats", varargs...)
	ret0, _ := ret[0].(*stats.PostStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostStats indicates an expected call of GetPostStats.
func (mr *MockStatsServiceClientMockRecorder) GetPostStats(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostStats", reflect.TypeOf((*MockStatsServiceClient)(nil).GetPostStats), varargs...)
}

// GetTopPosts mocks base method.
func (m *MockStatsServiceClient) GetTopPosts(arg0 context.Context, arg1 *stats.GetTopPostsRequest, arg2 ...grpc.CallOption) (*stats.TopPostsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTopPosts", varargs...)
	ret0, _ := ret[0].(*stats.TopPostsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPosts indicates an expected call of GetTopPosts.
func (mr *MockStatsServiceClientMockRecorder) GetTopPosts(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPosts", reflect.TypeOf((*MockStatsServiceClient)(nil).GetTopPosts), varargs...)
}

// GetTopUsers mocks base method.
func (m *MockStatsServiceClient) GetTopUsers(arg0 context.Context, arg1 *stats.GetTopUsersRequest, arg2 ...grpc.CallOption) (*stats.TopUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTopUsers", varargs...)
	ret0, _ := ret[0].(*stats.TopUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopUsers indicates an expected call of GetTopUsers.
func (mr *MockStatsServiceClientMockRecorder) GetTopUsers(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopUsers", reflect.TypeOf((*MockStatsServiceClient)(nil).GetTopUsers), varargs...)
}
