services:
  stats:
    build:
      context: .
      dockerfile: stats/Dockerfile
    ports:
      - "50004:50004"
    depends_on:
      - stats-clickhouse
    networks:
      - sn-network
      - stats-network
    environment:
      CLICKHOUSE_HOST: stats-clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DB: stats
    restart: always

  stats-clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
    volumes:
      - stats-clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: stats
    networks:
      - stats-network
    restart: always

volumes:
  stats-clickhouse-data:

networks:
  stats-network:
    driver: bridge